name: Build Docker Image

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtimes: ["cpu", "rocm", "cuda"]

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: easimon/maximize-build-space@v10
        with:
          build-mount-path: /var/lib/docker/
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - name: Restart docker
        run: sudo service docker restart

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kagurazakanyaa/comfyui,ghcr.io/kagurazakanyaa/comfyui
          flavor: |
            latest=auto
            prefix=${{ matrix.runtimes }}-,onlatest=true

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ matrix.runtimes }}.dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
